## Oppgave 1: Lag grunnleggende geometrier (*5 poeng*)

I denne oppgaven skal du lage skreddersydde funksjoner for å lage geometrier. Vi starter med en veldig enkel funksjon, og går videre til å lage funksjoner som kan håndtere ugyldige inngangsverdier.


**1a**: Lag en funksjon kalt `create_point_geom()` som har to parametere (x_coord, y_coord). Funksjonen skal lage et shapely "Point" geometriobjekt og returnere det.


In [4]:
from shapely import Point

def create_point_geom(x,y):
    p = Point([x,y])
    return p


x = 10
y = 50
point1 = create_point_geom(x,y)

Test funksjonen din ved å kjøre disse kodecellene:

In [5]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
# Demonstrere bruken av funksjonen
point1 = create_point_geom(0.0, 1.1)
print(point1)
print(point1.geom_type)

POINT (0 1.1)
Point


**1b**: Lag en funksjon kalt **`create_line_geom()`** som tar en liste over Shapely Point-objekter som parameter kalt **`points`** og returnerer et LineString-objekt av disse inputpunktene. I tillegg bør du passe på at funksjonen brukes som den skal:

- Inne i funksjonen bør du først sjekke med `assert` -funksjonaliteten at inputen er en **liste** . Hvis noe annet enn en liste sendes til funksjonen, skal du returnere en feilmelding: `"Input skal være en liste"`
- Du bør også sjekke med `assert` at inputlisten inneholder **minst** to verdier. Hvis ikke, returner en feilmelding: `"LineString-objekt krever minst to punkt!"`
- Valgfritt: Til slutt bør du sjekke med `assert` at alle verdiene i inputlisten er ekte Shapely Points. Hvis ikke, returner en feilmelding: `"Alle listeverdier skal være Shapely Point-objekter!"`


In [6]:

from shapely import Point, LineString

def create_line_geom(points):
    # sjekk at input er en liste
    assert isinstance(points, list)

    
    assert len(points) >= 2

    for p in points:
        assert isinstance(p, Point)
    return LineString(points)


    

Demonstrer bruken av funksjonen din; Lag for eksempel et linjeobjekt med to punkter: `Point(45.2, 22.34)` & `Point(100.22, -3.20)` og lagre resultatet i en variabel kalt `line1`:

In [7]:
line1 = create_line_geom([Point(45.2,22.34),Point(100.22,-3.20)])

Kjør disse kodecellene for å sjekke løsningen din:

In [8]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
print(line1)
print(type(line1))

LINESTRING (45.2 22.34, 100.22 -3.2)
<class 'shapely.geometry.linestring.LineString'>


Sjekk om funksjonen din kontrollerer inputen riktig ved å kjøre denne kodecellen:

In [12]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
try:
    # Pass på noe annet enn en liste
    create_line_geom("Gi meg en linje")
except AssertionError:
    print("Fant en assertion-error. Listetesten fungerer.")
except Exception as e:
    raise e

Fant en assertion-error. Listetesten fungerer.


**1c**: Lag en funksjon kalt **`create_poly_geom()`** som har én parameter kalt **`coords`**. `coords`-parameteren skal inneholde **en liste med koordinattupler**. Funksjonen skal opprette og returnere et polygonobjekt basert på disse koordinatene.

- Inne i funksjonen bør du først sjekke med `assert` -functionality at inputen er en **liste**. Hvis noe annet enn en liste sendes for funksjonen, skal du returnere en feilmelding: `"Input skal være en liste"`
- Du bør også sjekke med `assert` at inputlisten inneholder **minst** tre verdier. Hvis ikke, returner en feilmelding: `"Polygon-objekt krever minst tre punkter!"`
- Sjekk datatypen til objektene i inputlisten. Alle verdier i inputlisten skal være tupler. Hvis ikke, returner en feilmelding: `"Alle listeverdier skal være koordinattupler!"` ved bruk av `assert`.
- **Valgfritt:** Tillat også en input som inneholder en liste med Shapely Point-objekter. Hvis `coords` inneholder en liste med Shapely Point-objekter, returner et polygon basert på disse punktene. Hvis inputen verken er en liste med tupler, eller en liste med punkter, returner en passende feilmelding ved å bruke `assert`.


In [ ]:
from shapely.geometry import Point, Polygon, LineString

def create_poly_geom(coords):
    #sjekk at input er en liste
    assert isinstance(coords, list), "inputten må være en liste"

    # sjekk at listen har minst 3 elementer
    assert len(coords) >= 3, "listen må ha mer enn 3 elem"

    # sjekk at enten alle er tupler eller alle er Points
    if all(isinstance(c, tuple) for c in coords):
        return Polygon(coords)
    elif all(isinstance(c, Point) for c in coords):
        return Polygon([(p.x, p.y) for p in coords])
    else:
        assert False, "alle listeverdier må være shsply objekter"


Demonstrer bruken av funksjonen. Lag for eksempel et polygon med tre punkter: `(45.2, 22.34)`, `(100.22, -3.20)` og `(70.0, 10.20)`.

In [18]:
poly1 = [(45.2, 22.34), (100.22, -3.20), (70.0, 10.20)]

In [19]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
print(poly1)
print(type(poly1))

[(45.2, 22.34), (100.22, -3.2), (70.0, 10.2)]
<class 'list'>


Sjekk om funksjonen din kontrollerer lengden på inputen riktig ved å kjøre denne kodecellen:

In [20]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
try:
    # Pass på noe annet enn en liste
    create_poly_geom("Lag et polygon")
except AssertionError:
    print("Listetesten fungerer")
except Exception as e:
    raise e

Listetesten fungerer


Det var det. Nå er du klar til å fortsette med oppgave 2.

## Oppgave 2: Attributter til geometrier (*5 poeng*)

**2a**: Lag en funksjon kalt `get_centroid()` som har én parameter kalt `geom`. Funksjonen bør ta en hvilken som helst form for Shapely-objekt som input, og returnere et midtpunkt av den geometrien. I tillegg bør du passe på at funksjonen brukes som den skal:

- Inne i funksjonen bør du først sjekke med `assert` -funksjonalitet at inputen er en Shapely Point, LineString eller Polygon geometri. Hvis noe annet enn et Shapely objekt sendes for funksjonen, bør du returnere en feilmelding: `"Input skal være en Shapely geometri!"`


In [ ]:


def get_centroid(geom):
    # sjekk at input er en shapely geometri (Point, LineString eller Polygon)
    assert isinstance(geom, (Point, LineString, Polygon)), "Input skal være en Shapely geometri!"
    
    # returner centroid
    return geom.centroid


Test og demonstrer bruken av funksjonen. Du kan for eksempel lage shapely-objekter ved å bruke funksjonene du opprettet i oppgave 1 og skrive ut informasjon om midtpunktene deres:


In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
centroid = get_centroid(poly1)
print(centroid)

Sjekk at assert-feilen fungerer som den skal:

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
try:
    # Bestå noe annet enn en Shapely geometri
    get_centroid("Gi meg en centroide.!")
except AssertionError:
    print("Fant en assertion-error. Geometri-testen virker.")
except Exception as e:
    raise e

**2b**: Lag en funksjon kalt `get_area()` med én parameter kalt `polygon`. Funksjonen skal ta et Shapely Polygon-objekt som input og returnerer arealet til den geometrien.

- Inne i funksjonen bør du først sjekke med `assert` -funksjonalitet at inputen er en Shapely Polygon-geometri. Hvis noe annet enn en liste sendes for funksjonen, bør du returnere en feilmelding: `"Input skal være et Shapely Polygon-objekt!"`

In [ ]:
# SKRIV DIN KODE HER OG FJERN LINJEN "raise NotImplementedError()"
raise NotImplementedError()

Test og demonstrer bruken av funksjonen:

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
area = get_area(poly1)
print(round(area, 2))

Sjekk at assert-feilen fungerer:

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
try:
    # Bestå noe annet enn en Shapely geometri
    get_area("Gi meg et areal!")
except AssertionError:
    print("Geometri-testen virker")
except Exception as e:
    raise e

**2c**: Opprett en funksjon kalt `get_length()` med parameter kalt `geom`. Funksjonen skal akseptere enten et Shapely LineString eller Polygon-objekt som input. Funksjonen skal sjekke typen inndata og returnerer lengden på linjen hvis input er LineString og lengden på den ytre ringen hvis input er Polygon. Hvis noe annet sendes til funksjonen, bør du returnere en `Error` `"'geom' skal være enten LineString eller Polygon!"`. (Bruk assert-funksjonalitet).


In [ ]:
# SKRIV DIN KODE HER OG FJERN LINJEN "raise NotImplementedError()"
raise NotImplementedError()

Test og demonstrer bruken av funksjonen:

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
line_length = get_length(line1)
print("Linjelengde:", round(line_length,2))

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
poly_exterior_length = get_length(poly1)
print("Polygon omkrets:", round(poly_exterior_length,2))

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!
try:
    # Send noe annet enn en Shapely LineString eller Polygon
    get_length(Point(1,2))
except AssertionError:
    print("Geometri-testen virker")
except Exception as e:
    raise e

## Docstrings

Har du lagt til en docstring til alle funksjonene du definerte? Hvis ikke, legg dem til nå :) En kort en-linjes docstring er nok i denne øvelsen.

Sjekk: inneholder alle funksjonene dine en docstring? 1 poeng tildeles automatisk dersom testen under består.

I tillegg kan du kjøre kodecellen nedenfor for å sjekke alle docstringene!

In [ ]:
# TEST-CELLE
## Ikke slett denne cellen, og nye kodeceller du lager til denne deloppgaven skal komme før denne!

# List opp alle funksjonene vi har laget
functions = [create_point_geom, create_line_geom, create_poly_geom, 
             get_centroid, get_area, get_length]

print("Mine funksjoner:\n")

for function in functions:
    # Skriv ut funksjonsnavn og docstring:
    print("-", function.__name__ +":", function.__doc__)

## Ferdig!